services:
  spark:
    image: apache/spark:3.4.0
    container_name: spark-demo
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-demo
    volumes:
      - ./:/app
    networks:
      - spark-network
    command: tail -f /dev/null

  python-app:
    image: python:3.9
    container_name: python-app-demo
    volumes:
      - ./:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge